- platform: generic
  still_image_url: IMAGE-URL
  name: Weather
- platform: mjpeg
  mjpeg_url: http://10.0.1.26:8080/?action=stream
  name: Outdoor

- platform: arlo
  username: EMAIL
  password: PASS
