homeassistant:
  name: Home
  customize: !include customize.yaml
  elevation: 94
  unit_system: imperial
  latitude: !secret home_lat
  longitude: !secret home_long
  time_zone: America/Chicago

sun:

zone:
  name: Work
  latitude: !secret work_lat
  longitude: !secret work_long
  radius: 500 
  icon: mdi:worker

zone 2:
  name: Bethany's House
  latitude: !secret bethany_lat
  longitude: !secret bethany_long
  radius: 500
  icon: mdi:heart

zone 3:
  name: Dan and Marilyn's
  latitude: !secret dan_lat
  longitude: !secret dan_long
  radius: 500
  icon: mdi:home-variant

zone 4:
  name: Wayne and Lisa's
  latitude: !secret wayne_lat
  longitude: !secret wanye_long
  radius: 500
  icon: mdi:home-variant

zone 5:
  name: Michael and Mandy's
  latitude: !secret michael_lat
  longitude: !secret michael_long
  radius: 500
  icon: mdi:home-variant

zone 6:
  name: Kimberly and Travis'
  latitude: !secret travis_lat
  longitude: !secret travis_long
  radius: 500
  icon: mdi:home-variant

proximity:
  home:
    devices:
      - device_tracker.owntracks_android 
    tolerance: 50
    unit_of_measurement: mi

apcupsd:
  host: 10.0.1.6
  port: 3551

#media_player:
#  platform: plex

# Checks for available updates
#updater:

# Allows you to issue voice commands from the frontend
#conversation:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Discover some devices automatically
#discovery:

http:
  api_password: !secret api_password
  server_port: 8123
  #Using nginx proxy to serve https over ipv4/ipv6

#Local MQTT Only (local devices publish here, and I subscribe over ssl via bridged remote MQTT)
mqtt:
  broker: 127.0.0.1
  port: 1883
  keepalive: 60
  username: !secret owntracks_user
  password: !secret owntracks_password

device_tracker:
  - platform: owntracks
  - platform: bluetooth_tracker
    interval_seconds: 30
  - platform: nmap_tracker
    hosts: 10.0.1.41/32
    home_interval: 10 
  - platform: nmap_tracker
    hosts: 10.0.1.38/32
    home_interval: 10

climate:
  platform: radiotherm
  host:
    - 10.0.1.29
  hold_temp: True

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: notify_push_android

influxdb:
  host: localhost
  username: !secret influx_user
  password: !secret influx_password

ifttt:
  key: !secret ifttt_key

light:
  - platform: limitlessled
    bridges:
      - host: 10.0.1.47
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: andrew_bedroom
        - number: 2
          type: rgbw
          name: andrew_monitor_backlight

zwave:
  usb_path: /dev/zwave
  config_path: /opt/python-openzwave/openzwave/config

wemo:

emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - script


alexa: !include alexa.yaml
camera: !include camera.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
automation: !include automation.yaml
group: !include group.yaml
scene: !include scene.yaml
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
shell_command: !include shell_command.yaml
