- platform: miflora
  mac: "c4:7c:8d:63:34:c8"
  name: Garden
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: darksky
  api_key: API_KEY
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - humidity

- platform: usps
  username: USERNAME
  password: PASSWORD

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: network_in
      arg: eno1
    - type: network_out
      arg: eno1
    - type: last_boot

- platform: apcupsd
  resources:
    - loadpct
    - bcharge
    - timeleft

- platform: mqtt
  state_topic: 'bed-toggle/state'
  name: 'Bed Toggle Switch'
  qos: 1
  value_template: "{{ value_json.enabled }}"

- platform: mqtt
  state_topic: "owntracks/owntracks/Android"
  name: "Andrew Phone Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "moon"
  name: "Moon Phase"
  value_template: "{{ value_json.phase }}"


####################
# BEGIN SONOFF POW #
####################
- platform: mqtt
  name: Sonoff Pow Yesterday Energy
  unit_of_measurement: "kWh"
  state_topic: "tele/sonoff_pow_1/YESTERDAY_ENERGY"

- platform: mqtt
  name: Sonoff Pow Today Energy
  unit_of_measurement: "kWh"
  state_topic: "tele/sonoff_pow_1/TODAY_ENERGY"

- platform: mqtt
  name: Sonoff Pow Current
  unit_of_measurement: "Amps"
  state_topic: "tele/sonoff_pow_1/CURRENT"

- platform: mqtt
  name: Sonoff Pow Power
  unit_of_measurement: "Watts"
  state_topic: "tele/sonoff_pow_1/CURRENT_POWER"

- platform: template
  sensors:
    sonoff_pow_today_cost:
      friendly_name: Sonoff Pow Today Cost
      entity_id: sensor.sonoff_pow_today_energy
      unit_of_measurement: "$"
      value_template: >-
        {{ states.sensor.sonoff_pow_today_energy.state  | multiply(0.1123) | round(2) }} 
    sonoff_pow_yesterday_cost:
      friendly_name: Sonoff Pow Yesterday Cost
      entity_id: sensor.sonoff_pow_yesterday_energy
      unit_of_measurement: "$"
      value_template: >-
        {{ states.sensor.sonoff_pow_yesterday_energy.state  | multiply(0.1123) | round(2) }}



###################
# MQTT THERMOSTAT #
###################

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Temperature"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.temp }}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Operating Mode"
  value_template: "{% if value_json.tmode == 0 %}Off{% elif value_json.tmode == 1 %}Heat{% elif value_json.tmode == 2 %}Cool{% elif value_json.tmode == 3 %}Auto{% endif %}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Fan Mode" 
  value_template: "{% if value_json.fmode == 0 %}Auto{% elif value_json.fmode == 1 %}Auto/Circulate{% elif value_json.fmode == 2 %}On{% endif %}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat State" 
  value_template: "{% if value_json.tstate == 0 %}Idle{% elif value_json.tstate == 1 %}Heating{% elif value_json.tstate == 2 %}Cooling{% endif %}"

- platform: mqtt
  state_topic: "thermostat"
  unit_of_measurement: "°F"
  name: "Thermostat Setpoint"
  value_template: "{{ value_json.setpoint }}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Fan Status"
  value_template: "{% if value_json.fstate == 0 %}Off{% elif value_json.fstate == 1 %}On{% endif %}"

- platform: mqtt
  state_topic: "thermostat"
  name: "Thermostat Hold"
  value_template: "{% if value_json.hold == 1 %}True{% else %}False{% endif %}"


#######
# DHT #
#######

- platform: mqtt
  state_topic: "sensor/dht_mini_1"
  unit_of_measurement: "°F"
  name: "Andrew Room Temperature"
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_1"
  name: "Andrew Room Humidity"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_1"
  name: "Andrew Room Heat Index"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.heat_index }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_2"
  name: "Rack Exhaust Temperature"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_2"
  name: "Rack Exhaust Humidity"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"

- platform: mqtt
  state_topic: "sensor/dht_mini_2"
  name: "Rack Exhaust Heat Index"
  unit_of_measurement: "°F"
  value_template: "{{ value_json.heat_index }}"


#####################
# PHYSICAL SECURITY #
#####################

- platform: mqtt
  state_topic: "sensor/backdoor"
  name: "Backdoor"
  value_template: "{{ value_json.opened }}"

- platform: mqtt
  state_topic: "sensor/frontdoor"
  name: "Frontdoor"
  value_template: "{{ value_json.opened }}"


#############
# TEMPLATES #
#############

- platform: template
  sensors:
    front_door_status:
      value_template: >-
        {%- if is_state("sensor.frontdoor", "true") %}
          Open
        {%- else %}
          Closed
        {%- endif %}
      friendly_name: 'Front Door Status'

- platform: template
  sensors:
    back_door_status:
      value_template: >-
        {%- if is_state("sensor.backdoor", "true") %}
          Open
        {%- else %}
          Closed
        {%- endif %}
      friendly_name: 'Back Door Status'

- platform: template
  sensors:
    magnet_1:
      value_template: >-
        {%- if is_state("sensor.linear_unknown_type2001_id0102_alarm_level_2_1", "255") -%}
          open
        {%- else -%}
          closed
        {%- endif %}
    magnet_2:
      value_template: >-
        {%- if is_state("sensor.linear_unknown_type2001_id0102_alarm_level_4_1", "255") -%}
          open
        {%- else -%}
          closed
        {%- endif %}
    magnet_3:
      value_template: >-
        {%- if is_state("sensor.linear_unknown_type2001_id0102_alarm_level_5_1", "255") -%}
          open
        {%- else -%}
          closed
        {%- endif %}
    pir:
      value_template: >-
        {%- if is_state("sensor.linear_unknown_type2002_id0203_alarm_level_3_1", "255") -%}
          occupied
        {%- else -%}
          unoccupied
        {%- endif %}
